### PR TITLE
Adding support for MPRIS track informations

### PR DESCRIPTION
**Pull request by cg-Kdaf**
Previously, only chromium was communicating the track infos to the system.
This patch allows the electron app to give to the system more informations and control about the music played.

I also added the ability to click on the tray icon to hide/show the window (I just added the hide).

### CODE REVIEW

**Comment by duzda** [comment]
Hello, getting this error, when trying to run the program via electron . after npm install. Definitely some problem caused by dbus.node, which is used by mpris-service. The current release version runs with no problems.

Screenshot_2021-07-06-17-01-09

**Comment by cg-Kdaf** [comment]
it was a problem of mpris services version. It should be working fine now, let me know.

**Comment by fminetto** [comment]
I'll test on my laptop, and launch on snap store. Thakks

**Comment by duzda** [comment]
Seems to be working flawlessly now! Amazing addition, thanks :)

**Comment by cg-Kdaf** [comment]
@fminetto Could you take a look and merge it if you think it is useful for everyone ? I also have another patch coming about performance improvement.

**Comment by cg-Kdaf** [comment]
As the duzda's pull request is far behind this one, I close it.

**Pull request closed without merging**
